language: julia

julia:
  - 1.3

codecov: true

coveralls: true

branches:
  only: master

script:
  - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/wildart/TOML.jl.git", rev="master")); Pkg.activate("."); Pkg.test("Qaze", coverage=true);'
