language: julia

julia:
  - 1.3

codecov: true

coveralls: true

branches:
  only: master

script:
  - julia -e 'using Pkg; Pkg.add("https://github.com/wildart/TOML.jl.git"); Pkg.test("Qaze", coverage=true);'
