language: julia

julia:
  - 1.3

codecov: true

coveralls: true

branches:
  only: master

script:
  - julia -e 'using Pkg;'
  - julia -e 'Pkg.add(PackageSpec(url="https://github.com/wildart/TOML.jl.git", rev="master"))'
  - julia -e 'Pkg.activate(".");'
  - julia -e 'Pkg.test("Qaze", coverage=true);'
