title = "Qwind config file"

[general]
save_path = "cak_logs.json"
verbosity = 0

[bh]
M = 1e8
mdot = 0.5
spin = 0.0
eta = 0.057

[disk]
inner_radius = 6.0
outer_radius = 1600.0
mu = 1.0

[grids]
r_min = 0.0
z_min = 0.0
r_max = 10000.0
z_max = 10000.0
n_r_disk = 1001
n_vacuum = 1e2
tree_initial_divisions = 2
cell_optical_thickness = 0.2

[radiation]
f_uv = "auto" 
f_x = "auto"
integral_rtol = 1e-2
analytical_fm = true
tau_uv_geometry = "disk"
disk_uv_fraction = true 
no_tau_uv = false
no_tau_uv_z = false 
tau_uv_include_fm = false
constant_frad_height = 1.0

[wind]
initial_radius = "warm_radius" 
final_radius = 2000.0
number_streamlines = 60
iterations = 5
log_spaced = true
wind_temperature = 2.5e4 
initial_conditions = "manual"
n_0 = "cak"
v_0 = "thermal"
z_0 = 0.0
solver_rtol = 1e-2
gravity_only = false 
nofm = false
consistent_mdot = false