title = "Qwind config file"

[general]
save_path = "refin.json"
verbosity = 0

[bh]
M = 1e8
mdot = 0.5
spin = 0.0
eta = 0.057

[disk]
inner_radius = 6.0
outer_radius = 1600.0
mu = 1.0

[grids]
r_min = 0.0
z_min = 0.0
r_max = 3000.0
z_max = 3000.0
n_r = 50
n_z = 51
n_r_disk = 501 
n_phi_disk = 251
n_vacuum = 1e2
log_spaced = false 
tree_initial_divisions = 2
cell_optical_thickness = 0.2

[radiation]
f_uv = "auto" 
f_x = "auto"
non_adaptive_integral = false
integral_rtol = 1e-3
analytical_fm = true
tau_uv_geometry = "disk"
disk_uv_fraction = true 
no_tau_uv = false
no_tau_uv_z = false 
tau_uv_include_fm = true
tau_uv_ignore_grid = false 
tau_x_ignore_grid = false 

[wind]
initial_radius = "warm_radius" 
final_radius = 2000.0
number_streamlines = 60
iterations = 5
log_spaced = false
wind_temperature = "disk"
initial_conditions = "manual"
n_0 = 1e9
v_0 = "thermal"
z_0 = 0.0
solver_rtol = 1e-2
gravity_only = false 
nofm = false
consistent_mdot = false