title = "Qwind config file"

[general]
save_dir = "julia_cd_5_10"
verbosity = 0

[bh]
M = 1e8
mdot = 0.5
spin = 0.0
eta = 0.057

[disk]
inner_radius = 6.0
outer_radius = 1600.0
mu = 1.0

[grids]
r_min = 6.0
z_min = 1e-3
r_max = 3000.0
z_max = 1000.0
n_r = 1000
n_z = 1001
n_r_disk = 501 
n_phi_disk = 251

[radiation]
f_uv = 0.85 
f_x = 0.15 
non_adaptive_integral = false
adaptive_integral_epsrel = 1e-4
analytical_fm = false
tau_uv_geometry = "disk"
disk_uv_fraction = true 
no_tau_uv = false
no_tau_uv_z = false 
tau_uv_include_fm = false
tau_uv_ignore_grid = false 
tau_x_ignore_grid = false 

[wind]
initial_radius = 6.0
final_radius = 1600.0
number_streamlines = 80
iterations = 10
log_spaced = true
rho_shielding = 1e2
wind_temperature = "disk"
initial_conditions = "manual"
rho_0 = 5e10
v_0 = "thermal"
z_0 = 1.0
solver_rtol = 1e-2
